
workdir: experiments/GaussianSLAM
run_name: eccv_reproduce

# planning parameters
policy: 
  name: frontier
  planning_queue_size: 30

use_wandb: True

H_reg_lambda: 0.000001
num_frames: &total_frames 2100
checkpoint_interval: 1000
# number of keyframes for local mapping
forward_step_size: 0.05
turn_angle: 5.
path_end_weight: 30.
opacity_pixel_weight: 0.0001

report_global_progress_every: 10
report_iter_progress: true

save_checkpoints: true
scene_radius_depth_ratio: 3
use_wandb: false
img_height: 800
img_width: 800
downsample_pcd: 4

# mapping parameters
mapping:
  add_new_gaussians: true
  add_rand_gaussians: false
  densify_dict:
    final_removal_opacity_threshold: 0.005
    removal_opacity_threshold: 0.005
    densify_every: 100
    grad_thresh: 0.0002
    num_to_split_into: 2
    remove_big_after: 3000
    reset_opacities_every: 3000
    start_after: 500
    stop_after: 5000
    depth_error_ratio: 10
    add_random_gaussians: false
  ignore_outlier_depth_loss: false
  loss_weights:
    depth: 1.0
    im: 0.5
  lrs:
    cam_trans: 0.0
    cam_unnorm_rots: 0.0
    log_scales: 0.01
    logit_opacities: 0.05
    means3D: 0.001
    rgb_colors: 0.0025
    unnorm_rotations: 0.001
  num_iters: 60
  prune_gaussians: true
  pruning_dict:
    # Remove gaussians with opacity below this threshold
    final_removal_opacity_threshold: 0.0001
    removal_opacity_threshold: 0.0001
    prune_every: 40
    remove_big_after: 100
    reset_opacities: false
    reset_opacities_every: 500
    start_after: 0
    stop_after: *total_frames
  sil_thres: 0.5
  use_gaussian_splatting_densification: false
  use_l1: true
  use_sil_for_loss: false

# tracking parameters
tracking:
  depth_loss_thres: 20000
  forward_prop: true
  ignore_outlier_depth_loss: false
  loss_weights:
    depth: 1.0
    im: 0.5
  lrs:
    cam_trans: 0.002
    cam_unnorm_rots: 0.0004
    log_scales: 0.0
    logit_opacities: 0.0
    means3D: 0.0
    rgb_colors: 0.0
    unnorm_rotations: 0.0
  num_iters: 40
  sil_thres: 0.89
  use_depth_loss_thres: true
  use_gt_poses: true
  use_l1: true
  use_sil_for_loss: true
  visualize_tracking_loss: true

# Exploration parameters:
explore:
  use_frontier: true 
  height_range: 0.6
  prune_invisible: false
  sample_view_num: 256
  sample_range: 1.
  min_range: 0.5
  cell_size: 0.05
  centering: True
  shortcut_path: True
  add_random_gaussians: True
  frontier_select_method: "combined"